export enum AlertType {
  SUCCESS,
  FAILED,
  AUTHENTICATIONERROR,
  INVALIDTOKEN,
  BADREQUEST,
  UNAUTHORIZEDREQUEST,
  RESOURCEDOESNOTEXIST,
  INTERNALSERVERERROR,
  UNKNOWNERROR,
  AUTHENTICATIONSTART,
  PASSWORDRESETSUCCESS,
  PASSWORDEXPIRED,
  AUTHENTICATIONSUCCESS,
  TWOFACTORAUTHENTICATIONREQUIRED
}

export interface Alert {
  type: AlertType;
  message: string;
}
